### ISSUE TITLE
能否将卡片效果和图片放在一起发送

### ISSUE THREAD

**Issue by WKyouka** [I-linmeng-I/YGOAssistant#1]
感觉一张卡分两次发怪怪的

新问题：在查了一次卡后，之后发数字的话，bot会不停地给你发卡，比方我查了一个闪刀姬，bot会给出一些选项，然后之后我只要发数字，bot就会给你返回结果，这个逻辑有待改善，至少不应该单纯地用数字作为指令。

**Comment by I-linmeng-I** [comment]
是，当初是考虑说如果列表里有10张卡，然后你想来回看过去的话得重复查和重复输入数字太麻烦了。确实得改下指令

卡图和效果分开发是有时候卡图会莫名其妙被QQ和谐了。如果一起发就一起被吞了。分开发好歹能保证效果肯定发的出来

**Comment by I-linmeng-I** [comment]
现在修改了了查卡的指令，现在变成`进入单卡 数字`了。
下个最新版就行了
